

name: PikaOS kinetic

on:
  workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
    - uses: actions/checkout@v3

    - name: Install needed packages
      run: apt update && apt install debootstrap -y

    - name: Build ISO
      run: ./build.sh
      
        # http://man7.org/linux/man-pages/man1/date.1.html
    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d%H%M")"
      shell: bash

    - uses: actions/cache@v3
      with:
        path: builds/
        key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}

#     - uses: actions/upload-artifact@v3
#       with:
#         name: PikaOS 22.10
#         path: builds/
